CREATE TABLE ONEINSIGHT_REPOSITORY (
  APPLICATION VARCHAR(100),
  MODULE VARCHAR(200),
  SCREEN VARCHAR(100),
  LOCATOR_REFERENCE VARCHAR(100),
  LOCATOR_NAME VARCHAR(100),
  LOCATOR_VALUE VARCHAR(100),
  CONSTRAINT LOCATOR_REFERENCE_UNIQUE UNIQUE (LOCATOR_REFERENCE)
  ); COMMIT;
  
CREATE TABLE ONEINSIGHT_PROPERTIES(
  PROPERTY_REFERENCE VARCHAR(100),
  PROPERTY_VALUE VARCHAR(100),
  CONSTRAINT PROPERTY_REFERENCE_UNIQUE UNIQUE (PROPERTY_REFERENCE)
  ); COMMIT;

CREATE TABLE EDIT_CHECK_SQL(
  EDIT_CHECK_REFERENCE VARCHAR(100),
  EDIT_CHECK_SQL VARCHAR (2000),
  CONSTRAINT EDIT_CHECK_REFERENCE_UNIQUE UNIQUE (EDIT_CHECK_REFERENCE)
  ); COMMIT;

CREATE TABLE ONEINSIGHT_ENV(
  ENV_NAME VARCHAR(100),
  ENV_URL VARCHAR(200),
  ENV_USER_NAME VARCHAR(200),
  ENV_USER_PWD VARCHAR(200),
  CONSTRAINT ENV_NAME_UNIQUE UNIQUE (ENV_NAME)
  ); COMMIT;

CREATE TABLE EXCEPTION_SEVERITY
(
EXCEPTION_CODE VARCHAR(200),
EXCEPTION_SEVERITY VARCHAR(200)
CONSTRAINT EXCEPTION_CODE_UNIQUE UNIQUE (EXCEPTION_CODE)
); COMMIT;

CREATE TABLE MICROSERVICE_QUERY_PARAM
(
MODULE_NAME VARCHAR(200),
ENDPOINT_NAME VARCHAR(200),
ARG_NAME VARCHAR(200),
ARG_VALUE VARCHAR(200)
CONSTRAINT ENDPOINT_NAME_UNIQUE UNIQUE (ENDPOINT_NAME)
); COMMIT;